const motivasi = {
  keluarga: [
    "Kadang kita nggak sadar, doa orang rumah yang bikin kita kuat sampai hari ini.",
    "Pulanglah, meski nggak ada kabar bahagia. Mereka cuma mau lihat kamu utuh.",
    "Keluarga itu bukan tentang seberapa sering ketemu, tapi seberapa tulus merindukan.",
    "Ada rasa aman yang cuma bisa kita temuin di tatapan ibu.",
    "Ayah nggak banyak bicara, tapi tangannya yang lelah itu bukti cinta yang nggak pernah habis.",
    "Keluarga itu tempat di mana kita boleh hancur, tapi selalu dibangun lagi.",
    "Kadang rumah terasa sempit, tapi di luar sana dunia jauh lebih dingin.",
    "Kamu nggak harus sempurna buat dicintai keluarga.",
    "Orang rumah nggak butuh cerita lengkapmu, cukup lihat kamu senyum mereka udah lega.",
    "Keluarga itu nggak selalu harmonis, tapi mereka yang paling kencang ngejagain kamu diam-diam.",
    "Pulanglah sebelum doa mereka berubah jadi air mata.",
    "Meski jauh, hati selalu nemuin jalan buat pulang.",
    "Keluarga nggak pernah tanya kamu sukses atau gagal, mereka cuma tanya: 'Kamu udah makan?'.",
    "Ada banyak cara bilang sayang, dan keluarga sering melakukannya tanpa kata.",
    "Kadang kita lupa, rumah adalah tempat kita diampuni tanpa syarat.",
    "Keluarga bukan cuma darah, tapi juga mereka yang nggak ninggalin saat semua orang pergi.",
    "Mungkin kamu nggak paham kerasnya mereka, tapi itu cara mereka melindungi.",
    "Jangan biarkan ego bikin jarakmu sama keluarga makin jauh.",
    "Mereka mungkin nggak ngerti mimpimu, tapi tetap doain kamu diam-diam.",
    "Di dunia yang sibuk, keluarga adalah jeda.",
    "Kadang kita baru sadar berharganya rumah saat udah nggak bisa pulang.",
    "Ada bahagia yang cuma muncul saat duduk makan bareng keluarga.",
    "Meski nggak sempurna, keluarga tetap rumah paling nyaman.",
    "Mereka nggak minta kamu jadi hebat, cuma pengen kamu baik-baik aja.",
    "Keluarga nggak pernah benar-benar pergi, mereka selalu ada di hatimu.",
    "Pulang bukan tentang jarak, tapi tentang hati yang mau kembali.",
    "Orang tua nggak selalu bilang 'aku sayang kamu', tapi mereka kerja keras demi kamu.",
    "Kadang yang kamu butuh cuma segelas teh buatan rumah.",
    "Meski berantem, keluarga tetap orang yang pertama kali datang saat kamu jatuh.",
    "Rumah itu tempat di mana rasa lelahmu dipahami.",
    "Keluarga nggak pernah menuntut balas budi, cukup lihat kamu bahagia.",
    "Kadang doa ibu lebih kuat dari semua rencana yang kamu susun.",
    "Ayah nggak pernah minta dipuji, tapi dia selalu jadi tembok yang kamu sandarin.",
    "Rumah adalah tempat di mana kamu boleh jadi dirimu sepenuhnya.",
    "Meski jauh di mata, keluarga selalu dekat di doa.",
    "Keluarga itu nggak selalu terlihat rapi, tapi di dalamnya ada cinta yang berantakan tapi nyata.",
    "Kadang yang kita cari di luar sebenarnya sudah ada di rumah.",
    "Pulanglah, sebelum rindu mereka berubah jadi penyesalan.",
    "Keluarga itu sederhana: saling menjaga meski tak selalu setuju.",
    "Kadang kita terlalu sibuk mengejar dunia, sampai lupa orang rumah menunggu kabar.",
    "Meski nggak selalu setuju, keluarga tetap yang paling peduli.",
    "Rumah itu tempat di mana air mata nggak perlu disembunyikan.",
    "Keluarga nggak pernah mengukur kamu dari nilaimu, tapi dari hatimu.",
    "Kadang kita butuh pergi biar ngerti arti pulang.",
    "Keluarga nggak selalu ngomong sayang, tapi kamu tahu dari cara mereka ngelihat kamu.",
    "Rumah bukan cuma alamat, tapi juga perasaan aman.",
    "Kadang yang kamu butuh cuma pelukan ibu dan diam.",
    "Ayah itu pahlawan yang jarang dapat panggung.",
    "Keluarga itu orang-orang yang tetap ada meski tahu kekuranganmu.",
    "Meski dunia nggak ramah, rumah selalu terbuka buatmu.",
    "Keluarga itu sabar menunggu meski kamu sering lupa pulang.",
    "Kadang doa orang tua jadi alasan kita bertahan.",
    "Keluarga nggak selalu sempurna, tapi mereka selalu jadi alasan kamu berdiri lagi.",
    "Rumah adalah tempat di mana hatimu istirahat.",
    "Kadang yang kita butuh cuma duduk bareng tanpa bicara.",
    "Keluarga itu memaafkan sebelum kamu minta maaf.",
    "Meski nggak paham ceritamu, mereka tetap dengerin.",
    "Pulang bukan kelemahan, tapi keberanian untuk kembali.",
    "Keluarga nggak pernah hitung berapa kali kamu jatuh.",
    "Rumah itu tempat di mana masa lalu nggak jadi beban.",
    "Kadang yang bikin kita kuat adalah mereka yang diam-diam mendoakan.",
    "Keluarga itu orang yang mau terima kamu meski kamu nggak sempurna.",
    "Meski lelah, mereka tetap siap denger ceritamu.",
    "Keluarga nggak pernah biarin kamu jalan sendirian.",
    "Rumah itu tempat di mana semua salahmu bisa diperbaiki.",
    "Kadang yang bikin kita tenang adalah senyum orang rumah.",
    "Keluarga itu nggak akan ninggalinmu meski semua orang pergi.",
    "Pulanglah, meski cuma sebentar.",
    "Keluarga itu cinta tanpa syarat.",
    "Rumah adalah tempat di mana kamu diterima apa adanya.",
    "Meski banyak kekurangan, keluarga tetap milikmu.",
    "Kadang yang kamu cari di luar cuma ilusi, nyatanya ada di rumah.",
    "Keluarga nggak pernah bosan mendoakanmu.",
    "Rumah itu tempat kamu bisa nangis tanpa takut dihakimi.",
    "Kadang kita baru paham berharganya rumah saat kehilangan.",
    "Keluarga itu tetap ada meski kamu menjauh.",
    "Rumah itu tempat di mana hati pulang tanpa takut.",
    "Kadang yang paling kuat adalah orang rumah yang diam-diam terluka demi kamu.",
    "Keluarga nggak pernah menuntut kamu jadi sempurna.",
    "Rumah adalah tempat di mana cinta nggak pernah habis.",
    "Meski jauh, doa mereka tetap sampai.",
    "Keluarga itu alasan kamu bertahan meski dunia jatuh.",
    "Rumah adalah pelukan yang nggak pernah menolak.",
    "Kadang yang kamu butuh cuma lihat senyum ibu.",
    "Keluarga itu yang tetap nyari kamu saat kamu hilang."
  ],

  ekonomi: [
    "Uang memang penting, tapi jangan sampai bikin kamu lupa cara bahagia.",
    "Kerja keras itu penting, tapi jangan lupa istirahat.",
    "Rezeki nggak selalu datang cepat, tapi dia nggak pernah salah alamat.",
    "Kadang kita kerja bukan buat kaya, tapi buat bertahan.",
    "Hidup nggak melulu tentang punya banyak, tapi cukup dan tenang.",
    "Jangan bandingin dompetmu sama orang lain, tiap orang punya waktunya.",
    "Uang bisa beli banyak hal, tapi nggak bisa beli ketenangan hati.",
    "Kadang kita lupa, sehat itu rezeki terbesar.",
    "Rezeki nggak cuma soal uang, tapi juga kesempatan dan orang baik di sekitar.",
    "Jangan takut mulai dari nol, semua orang sukses pernah di titik itu.",
    "Kerja keras itu wajib, tapi jangan sampai hilang arah.",
    "Kadang kita terlalu sibuk cari uang, sampai lupa nikmatin hidup.",
    "Rezeki akan datang di waktu yang tepat, bukan saat kamu panik.",
    "Nggak semua yang kelihatan kaya beneran tenang hatinya.",
    "Kadang cukup itu lebih bahagia daripada berlebihan tapi gelisah.",
    "Hidup sederhana bukan berarti hidup kekurangan.",
    "Jangan sampai kerja buat hidup, malah bikin lupa hidup.",
    "Rezeki nggak akan tertukar, tapi usaha tetap harus jalan.",
    "Kadang kita perlu berhenti sebentar biar nggak lupa tujuan.",
    "Jangan sampai uang bikin kamu kehilangan kemanusiaan.",
    "Kerja keras itu investasi, bukan hukuman.",
    "Rezeki nggak cuma di gaji, tapi di orang yang dukung kamu.",
    "Jangan takut miskin, takutlah kalau kamu malas.",
    "Kadang kehilangan uang itu pelajaran, bukan akhir.",
    "Hidup hemat itu bukan pelit, tapi bijak.",
    "Rezeki nggak selalu datang dari jalan yang kamu duga.",
    "Kerja keras itu pilihan, tapi bahagia itu wajib.",
    "Jangan kerja sampai lupa punya hati.",
    "Kadang cukup itu lebih aman daripada berlebihan.",
    "Uang bisa beli rumah, tapi nggak bisa beli rumah yang nyaman di hati.",
    "Rezeki akan datang meski jalannya memutar.",
    "Jangan berhenti berusaha cuma karena hasilnya belum kelihatan.",
    "Kerja keras itu nyelamatin, tapi jangan sampe bikin lupa diri.",
    "Kadang kehilangan uang bikin kita ngerti arti syukur.",
    "Hidup nggak harus kaya untuk bahagia.",
    "Rezeki nggak melulu soal materi, tapi juga kesehatan dan waktu.",
    "Jangan takut gagal, semua orang sukses pernah gagal.",
    "Kerja keras itu proses, hasilnya bonus.",
    "Kadang yang kita butuh cuma cukup, bukan segalanya.",
    "Uang nggak selalu bikin hidup lebih mudah.",
    "Rezeki itu rahasia Tuhan, tugas kita cuma usaha.",
    "Jangan biarkan uang jadi satu-satunya tujuan.",
    "Kerja keras itu bentuk sayang ke diri sendiri.",
    "Kadang rezeki datang dari tempat yang nggak kita sangka.",
    "Uang itu penting, tapi bukan segalanya.",
    "Rezeki nggak akan datang kalau kamu cuma diam.",
    "Jangan biarkan lelah bikin kamu berhenti.",
    "Kerja keras itu ibadah kalau niatnya benar.",
    "Kadang kita butuh istirahat biar bisa lanjut lagi.",
    "Uang bisa bikin hidup nyaman, tapi bukan berarti bahagia.",
    "Rezeki datang kalau kamu siap menerimanya.",
    "Jangan terlalu mikirin uang sampai lupa nikmatin hidup.",
    "Kerja keras itu bagian dari perjalanan, bukan tujuan akhir.",
    "Kadang cukup itu udah lebih dari cukup.",
    "Uang nggak bisa ganti waktu yang hilang.",
    "Rezeki nggak akan kemana kalau memang untukmu.",
    "Jangan kerja sampai lupa punya kehidupan.",
    "Kerja keras itu cara kita menghargai hidup.",
    "Kadang rezeki datang dari kebaikan kecil.",
    "Uang itu alat, bukan segalanya.",
    "Rezeki nggak melulu dari kerja keras, tapi juga dari doa.",
    "Jangan biarkan uang bikin kamu lupa siapa dirimu.",
    "Kerja keras itu pilihan yang bijak.",
    "Kadang yang bikin kita kaya adalah rasa cukup.",
    "Uang nggak bisa beli cinta yang tulus.",
    "Rezeki akan datang meski dari arah yang nggak kamu lihat.",
    "Jangan takut berjuang demi hidup yang layak.",
    "Kerja keras itu bentuk tanggung jawab.",
    "Kadang kita lupa kalau rezeki itu luas.",
    "Uang nggak selalu bikin kita tenang.",
    "Rezeki nggak akan telat datang.",
    "Jangan sampai uang bikin kamu lupa bersyukur.",
    "Kerja keras itu wajar, tapi jangan sampe jadi beban.",
    "Kadang cukup itu bikin hati lebih damai.",
    "Uang nggak bisa beli masa lalu.",
    "Rezeki datang kalau kita nggak menyerah.",
    "Jangan biarkan uang jadi sumber semua masalah.",
    "Kerja keras itu tanda kamu mau maju.",
    "Kadang kehilangan uang nyelametin kita dari masalah.",
    "Uang itu penting, tapi hati yang damai lebih penting.",
    "Rezeki akan datang sesuai waktunya.",
    "Jangan takut kerja keras, takutlah kalau nggak berusaha."
  ],

 pendidikan: [
    "Kadang kita terlalu fokus sama nilai, sampai lupa kalau tujuan belajar itu biar kita ngerti, bukan cuma biar dapat angka tinggi.",
    "Nilai itu penting, tapi pengalaman jatuh bangun pas belajar bakal jauh lebih berharga nanti.",
    "Nggak apa-apa lambat, asal kamu tetap jalan. Dunia nggak cuma buat orang yang lari kencang.",
    "Belajar itu bukan lomba siapa cepat siapa menang, tapi tentang siapa yang nggak nyerah.",
    "Kadang kita bandingin diri sama teman sekelas, padahal kita nggak tahu seberapa keras mereka berjuang.",
    "Ujian itu cuma mengukur seberapa paham kamu sama materi, bukan seberapa bernilai dirimu.",
    "Nggak semua yang jenius itu bahagia, dan nggak semua yang biasa-biasa aja itu gagal.",
    "Sekolah ngajarin kita teori, hidup ngajarin kita cara jatuh dan bangkit lagi.",
    "Kalau hari ini kamu nggak ngerti pelajaran, besok masih ada kesempatan buat nyoba lagi.",
    "Banyak orang sukses yang dulu nilai sekolahnya biasa aja. Hidup nggak berhenti di rapor.",
    "Belajar itu kayak nanem pohon, hasilnya nggak langsung kelihatan, tapi suatu hari bakal berguna.",
    "Kadang guru terbaik kita bukan yang di kelas, tapi hidup yang bikin kita jatuh dan mikir lagi.",
    "Jangan minder cuma karena belum bisa, semua orang punya waktunya sendiri buat ngerti.",
    "Hafal materi itu gampang, tapi ngerti maksudnya itu yang butuh hati.",
    "Pelan-pelan aja, jangan sampai ambisi bikin kamu lupa istirahat.",
    "Jangan cuma ngejar lulus, tapi juga ngejar ngerti.",
    "Buku bisa kasih ilmu, tapi pengalaman kasih hikmah.",
    "Kamu bukan gagal, kamu cuma lagi proses.",
    "Kadang kita terlalu takut remedial, padahal remedial cuma ulang kesempatan, bukan akhir segalanya.",
    "Nggak semua hal yang dipelajari di sekolah bakal kepake, tapi proses belajarnya yang bikin kamu kuat.",
    "Belajar bukan buat nyenengin guru atau orang tua, tapi buat bekal kamu sendiri nanti.",
    "Orang pinter bisa kalah sama orang sabar yang terus belajar.",
    "IPK tinggi nggak menjamin kamu ngerti hidup.",
    "Pendidikan itu penting, tapi jangan sampai lupa belajar soal hati dan empati.",
    "Kalau gagal di ujian, bukan berarti gagal di hidup.",
    "Kadang kita belajar hal yang kita nggak suka, tapi siapa tahu nanti itu yang nyelametin hidup kita.",
    "Jangan takut nanya, orang pinter dulu juga pernah nggak tahu.",
    "Setiap orang punya cara belajar sendiri, jangan paksa ikut cara orang lain.",
    "Nggak semua pemenang itu yang paling cepat, kadang yang paling sabar yang bertahan.",
    "Pelajaran paling mahal itu sering kita dapat dari kesalahan.",
    "Sekolah nggak ngajarin segalanya, jadi jangan berhenti belajar di luar kelas.",
    "Biarpun kamu nggak dapet juara kelas, kamu masih bisa jadi juara di bidang lain.",
    "Kadang satu kalimat dari guru bisa kita inget seumur hidup.",
    "Jangan bandingkan bab 1 kamu sama bab 20 orang lain.",
    "Belajar itu maraton, bukan sprint.",
    "Kadang belajar itu bikin capek otak, tapi tenang, otak juga bisa dilatih kayak otot.",
    "Bukan siapa cepat yang menang, tapi siapa yang nggak nyerah.",
    "Guru terbaik itu kegagalan, asal kamu mau dengerin.",
    "Kalau nggak paham sekali coba lagi, kalau nggak paham dua kali coba lagi. Konsistensi itu kunci.",
    "Belajar bukan buat hari ini aja, tapi buat masa depan yang belum kamu lihat.",
    "Jangan cuma belajar biar lulus, tapi belajar biar nggak gampang dibohongi hidup.",
    "Kadang yang bikin kita paham itu bukan pelajaran, tapi cerita hidup orang lain.",
    "Gagal ujian itu sementara, tapi nyerah itu selamanya.",
    "Kamu nggak sendirian, semua orang pernah nggak ngerti pas pertama kali belajar.",
    "Kalau kamu nggak ngerti sekarang, itu bukan akhir cerita.",
    "Semua orang mulai dari nol, jangan malu kelihatan nggak bisa.",
    "Belajar itu proses seumur hidup, bukan cuma waktu sekolah.",
    "Sekali gagal nggak bikin kamu bodoh, nyerah baru bikin kamu kalah.",
    "Mimpi besar butuh proses panjang, dan belajar adalah langkah pertama.",
    "Kadang yang kita pikir nggak penting sekarang, ternyata jadi penyelamat nanti.",
    "Kalau kamu capek belajar, istirahat sebentar, tapi jangan berhenti.",
    "Jangan takut salah, salah itu tanda kamu lagi nyoba.",
    "Sukses itu bukan keberuntungan, tapi hasil dari belajar terus-menerus.",
    "Pendidikan itu bekal yang nggak bisa dicuri.",
    "Kalau kamu sabar, pelan-pelan semua bakal masuk akal.",
    "Hidup nggak selalu adil, tapi ilmu bisa bikin kamu lebih siap.",
    "Sekolah nggak ngajarin segalanya, tapi dia ngajarin cara belajar apapun.",
    "Kalau mau lebih pinter dari kemarin, cukup belajar sedikit demi sedikit.",
    "Jangan takut belajar hal baru meskipun udah dewasa.",
    "Kalau nggak ngerti, berarti waktunya tanya, bukan diem.",
    "Pendidikan itu bukan cuma untuk cari kerja, tapi untuk ngerti hidup.",
    "Nilai kecil nggak berarti masa depan kecil.",
    "Belajar itu perjalanan, nikmatin setiap langkahnya.",
    "Kalau gagal di satu bidang, coba di bidang lain, kamu nggak terbatas.",
    "Buku ngajarin teori, tapi dunia ngajarin realita.",
    "Kalau nggak bisa hafal, coba pahami. Kalau nggak paham, coba rasakan.",
    "Jangan tunggu motivasi datang, mulai aja dulu.",
    "Ilmu itu investasi seumur hidup.",
    "Nggak semua orang ngerti perjuanganmu, tapi suatu saat hasilnya akan kelihatan.",
    "Kadang hal kecil yang kamu pelajari hari ini bisa nyelametin hidup orang lain besok.",
    "Jangan cuma belajar dari buku, tapi juga dari orang-orang di sekitarmu.",
    "Sekolah bukan akhir, tapi awal dari perjalanan hidup.",
    "Kadang yang bikin kita paham itu waktu, bukan buku.",
    "Jangan minder sama orang yang lebih pinter, tapi belajar dari mereka.",
    "Nggak ada kata terlambat untuk mulai belajar.",
    "Belajar itu kayak nabung, sedikit-sedikit nanti jadi banyak.",
    "Kalau kamu berhenti belajar, berarti kamu berhenti tumbuh.",
    "Setiap guru punya cara, setiap murid punya waktu.",
    "Kadang yang bikin paham itu bukan teori, tapi praktek.",
    "Belajar itu kadang nggak enak, tapi hasilnya bikin senyum.",
    "Kalau nggak mulai sekarang, kapan lagi?",
    "Ilmu itu nggak ada habisnya, makin dicari makin banyak.",
    "Kamu nggak sendirian, banyak orang juga lagi belajar kayak kamu.",
    "Belajar itu bukan tentang cepat selesai, tapi tentang ngerti bener.",
    "Kalau capek, boleh istirahat, tapi jangan berhenti."
  ],
pertemanan: [
    "Nggak semua orang yang bareng kita sekarang akan bareng kita sampai akhir, dan itu nggak apa-apa.",
    "Kadang sahabat itu bukan yang selalu ada di foto, tapi yang selalu ada di hati.",
    "Bukan berarti kita nggak penting, kadang mereka cuma lagi sibuk berjuang di jalannya sendiri.",
    "Temen sejati nggak selalu hadir di momen bahagia, tapi selalu hadir di momen kita nggak punya siapa-siapa.",
    "Jangan ukur persahabatan dari seringnya ketemu, ukur dari seberapa tulus mereka ngerti kita.",
    "Kadang kita harus ikhlas kalau seseorang cuma jadi bagian cerita, bukan akhir cerita.",
    "Persahabatan itu bukan siapa duluan yang datang, tapi siapa yang tetap tinggal saat semua orang pergi.",
    "Temen yang beneran itu nggak akan bikin kita ngerasa bersaing, tapi saling dukung.",
    "Kita nggak bisa nyalahin semua orang yang menjauh, mungkin mereka juga punya luka sendiri.",
    "Pertemanan nggak harus tiap hari ngobrol, yang penting hatinya tetap nyambung.",
    "Kadang, temen yang udah jarang komunikasi, tiba-tiba dateng dan tetap hangat, itu berharga banget.",
    "Temen yang baik itu yang bikin kita bisa jadi diri sendiri tanpa takut di-judge.",
    "Nggak semua tawa di grup chat itu tulus, tapi kita hargai aja momen bahagianya.",
    "Temen yang peduli itu bukan yang selalu nanya kabar, tapi yang peka sama diam kita.",
    "Biarpun jauh, kalau hatinya deket, nggak akan ada kata kehilangan.",
    "Temen sejati akan ngerti kesibukan kita, tanpa harus nuntut kehadiran terus-menerus.",
    "Kadang orang yang paling sering bercanda sama kita, dia juga yang paling ngerti sedih kita.",
    "Kehilangan temen sakit, tapi kehilangan diri sendiri demi temen itu lebih sakit.",
    "Temen itu nggak harus banyak, cukup satu yang bener-bener tulus.",
    "Temen yang baik akan nyuruh kita istirahat, bukan nyuruh kita pura-pura kuat."
  ],
  orangtua: [
    "Kadang kita lupa, orang tua juga manusia yang bisa capek dan salah.",
    "Nggak semua orang tua bisa bilang ‘aku sayang kamu’, tapi mereka nunjukin lewat tindakan.",
    "Setiap omelan orang tua, ada rasa takut kehilangan di dalamnya.",
    "Kita sibuk nyari validasi dari orang lain, tapi lupa orang tua udah bangga dari awal.",
    "Orang tua nggak minta balas budi, mereka cuma mau lihat kita bahagia.",
    "Ada kalanya kita kesel sama mereka, tapi nanti kita sadar, mereka yang paling nggak tergantikan.",
    "Setiap kali kita pulang, ada hati yang tenang karena anaknya selamat.",
    "Orang tua sering nggak paham dunia kita, tapi mereka tetep coba ngerti.",
    "Kita nggak bisa milih lahir dari siapa, tapi kita bisa milih untuk sayang sama mereka.",
    "Orang tua itu orang pertama yang percaya sama kita, bahkan waktu kita nggak percaya sama diri sendiri.",
    "Mereka nggak selalu ngomong manis, tapi mereka selalu nyiapin yang terbaik buat kita.",
    "Suatu saat nanti, kita akan kangen sama suara mereka yang nyebelin.",
    "Orang tua nggak sempurna, tapi mereka berusaha jadi versi terbaik buat kita.",
    "Jangan tunggu momen kehilangan untuk sadar betapa berharganya mereka.",
    "Kita mungkin nggak sepaham, tapi kita sepakat saling sayang.",
    "Orang tua sering nyuruh kita makan, tapi lupa makan sendiri.",
    "Dulu kita digendong biar bisa tidur nyenyak, sekarang mereka cuma butuh kita pulang biar tenang.",
    "Mereka nggak pernah minta kita jadi orang hebat, cukup jadi orang baik.",
    "Setiap lelah mereka, terselip doa supaya kita nggak ngerasain yang sama.",
    "Suatu saat nanti, kita akan sadar kalau semua yang mereka larang, ada alasannya."
  ],
percintaan: [
    "Kita nggak pernah benar-benar selesai, hanya berhenti bicara.",
    "Kamu bukan nggak cukup baik, dia aja yang nggak tau cara menghargai.",
    "Lucu ya, kita dulu tiap hari ngobrol, sekarang cuma saling lihat story tanpa sapa.",
    "Mungkin kita terlalu terburu-buru untuk jatuh, tapi terlalu lama untuk melepaskan.",
    "Ada yang datang untuk tinggal, ada juga yang datang cuma untuk ngasih luka.",
    "Kamu nggak kehilangan dia, kamu cuma kehilangan orang yang pura-pura sayang.",
    "Bukan waktunya yang salah, tapi orangnya yang nggak tepat.",
    "Kadang aku rindu, tapi nggak berani bilang karena takut kamu nggak merasa sama.",
    "Cinta nggak pernah salah, cuma orangnya yang kadang nggak benar.",
    "Kita berjuang di kapal yang sama, tapi kamu lompat lebih dulu.",
    "Ada yang bilang cinta itu buta, tapi aku rasa cinta itu cuma nggak peduli.",
    "Lucu, aku dulu segalanya buatmu, sekarang aku cuma kenangan.",
    "Aku nggak nyesel pernah cinta kamu, cuma nyesel kenapa nggak cinta diri sendiri dulu.",
    "Kamu ngajarin aku cara percaya, lalu kamu sendiri yang bikin aku ragu.",
    "Beberapa orang pergi tanpa pamit, dan itu jauh lebih sakit dari sekadar perpisahan.",
    "Aku nggak nyari pengganti, aku cuma nyari tenang.",
    "Ternyata kehilanganmu bukan akhir, cuma awal dari belajar lagi untuk sendiri.",
    "Cinta itu kadang bukan tentang siapa yang kamu tunggu, tapi siapa yang mau bertahan.",
    "Kamu nggak pernah benar-benar hilang, cuma udah nggak di hatiku lagi.",
    "Sayang itu nggak cukup kalau dia nggak mau berjuang.",
    "Kita jatuh cinta pada versi terbaik dari seseorang, lalu kecewa saat lihat aslinya.",
    "Nggak semua yang manis di awal akan manis di akhir.",
    "Aku belajar bahwa rindu bisa jadi racun kalau orangnya nggak pernah pulang.",
    "Kamu pergi tanpa kata, tapi meninggalkan seribu tanya.",
    "Kadang kita bukan kehilangan orangnya, tapi kehilangan dirimu yang bahagia saat bersamanya.",
    "Cinta nggak selalu tentang memiliki, kadang cukup tahu dia bahagia walau bukan sama kita.",
    "Ada orang yang kita perjuangkan mati-matian, tapi dia malah nyerah begitu aja.",
    "Mungkin aku bukan rumah, tapi setidaknya aku pernah jadi tempatmu pulang.",
    "Hubungan itu nggak mati karena jarak, tapi karena berhentinya komunikasi.",
    "Kamu terlalu sibuk mencari yang sempurna sampai lupa menghargai yang setia.",
    "Terkadang, rasa sayang berubah jadi asing dalam semalam.",
    "Kamu nggak salah, aku juga nggak salah, kita cuma nggak cocok.",
    "Cinta yang sehat itu saling melengkapi, bukan saling menguras energi.",
    "Kita tumbuh di arah yang berbeda, dan itu bukan salah siapa-siapa.",
    "Aku nggak mau lagi cinta yang bikin aku lupa mencintai diriku sendiri.",
    "Ada orang yang cuma mampir di hidup kita untuk jadi pelajaran termahal.",
    "Nggak semua yang datang bawa kebahagiaan, ada yang datang bawa luka.",
    "Kadang kita nggak sadar, kita lagi berjuang sendirian di hubungan yang harusnya berdua.",
    "Cinta yang sebenarnya nggak bikin capek, yang bikin capek itu orangnya.",
    "Kita saling cinta, tapi nggak saling mengerti.",
    "Kamu nggak bisa maksa orang tetap tinggal kalau hatinya udah pergi.",
    "Cinta itu bukan drama, tapi kalau udah banyak air mata, itu tanda bahaya.",
    "Kalau dia sayang, dia nggak akan bikin kamu merasa sendirian di hubungan.",
    "Aku nggak nyesel mencintaimu, aku cuma nyesel nggak pergi lebih cepat.",
    "Kadang, yang kita butuhkan bukan pasangan baru, tapi hati yang sembuh.",
    "Cinta itu nggak cukup kalau cuma satu orang yang mau berjuang.",
    "Kamu ngajarin aku cara melepaskan, walau aku nggak pernah minta.",
    "Hubungan nggak hancur karena jarak, tapi karena udah nggak ada rasa yang dijaga.",
    "Cinta itu sederhana, yang ribet itu ekspektasi kita.",
    "Kita pernah punya mimpi yang sama, sampai kamu buat mimpimu sendiri.",
    "Kalau dia benar-benar mau, dia akan berusaha.",
    "Kamu nggak kehilangan dia, kamu cuma bebas dari orang yang salah.",
    "Aku nggak marah kamu pergi, aku cuma kecewa caramu meninggalkan.",
    "Hubungan itu soal usaha, bukan cuma janji manis di awal.",
    "Cinta itu nggak nyakitin, orangnya yang nyakitin.",
    "Nggak semua yang kita cintai akan cinta balik.",
    "Ada yang pergi tanpa alasan, dan itu bikin kita bertanya-tanya selamanya.",
    "Aku nggak minta kamu sempurna, aku cuma minta kamu tetap seperti di awal.",
    "Cinta itu butuh timbal balik, kalau cuma satu pihak itu namanya pengorbanan.",
    "Kadang yang kita tunggu nggak pernah balik.",
    "Kamu nggak salah mencintai, cuma salah percaya sama orang yang salah.",
    "Kalau dia sibuk, dia akan cari waktu, bukan alasan.",
    "Cinta nggak selalu bahagia, tapi harusnya nggak bikin luka setiap hari.",
    "Aku berhenti mengejar, bukan karena nggak sayang, tapi karena aku juga harus sayang sama diriku.",
    "Nggak ada yang abadi, bahkan rasa sayang pun bisa pudar.",
    "Kita pernah jadi 'kita', sekarang kita cuma 'kamu' dan 'aku'.",
    "Cinta itu bukan tentang siapa yang lebih sayang, tapi siapa yang nggak nyerah duluan.",
    "Aku nggak mau lagi jadi pilihan cadangan.",
    "Cinta itu nggak egois, kalau egois itu cuma nafsu memiliki.",
    "Kalau dia buat kamu merasa nggak cukup, berarti dia bukan orang yang tepat.",
    "Kadang kita cuma jatuh cinta sama kenangan, bukan orangnya lagi.",
    "Cinta nggak harus rumit, kalau rumit mungkin itu bukan cinta.",
    "Aku nggak nyesel, tapi aku juga nggak mau kembali.",
    "Kita pernah bahagia, itu udah cukup untuk aku kenang.",
    "Kalau dia mau pergi, bukain pintu, jangan tahan.",
    "Cinta yang benar nggak bikin kamu merasa sendirian.",
    "Nggak semua rasa rindu harus disampaikan.",
    "Kadang, mencintai dari jauh adalah cara terbaik untuk nggak saling melukai.",
    "Cinta itu nggak memenjarakan, cinta itu membebaskan.",
    "Aku nggak mau lagi berjuang sendirian di hubungan yang harusnya berdua.",
    "Kalau dia sayang, dia nggak akan bikin kamu mempertanyakan posisimu di hatinya.",
    "Kita bukan gagal, kita cuma selesai."
]
};


